version:  '3'
services:
  video-streaming-webserver:
    image:  video-streaming-webserver
    build:
      context: ./web-server
      dockerfile: Dockerfile
    container_name: video-streaming-webserver
    ports:
      - "4000:80"
    environment:
      - PORT=80
    restart: "no"