version:  '3'
services:
  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=mmivideostreamstorage
      - STORAGE_ACCESS_KEY=JvAtqthYnEwE5Itog95Z2Q/h6Dv2LsS0G6HblZ9hhaDm10PzIFGmG8x+znePP5JQlvbbq86mg3HH+AStAJwNtw==
    restart: "no"    
  video-streaming-webserver:
    image:  video-streaming-webserver
    build:
      context: ./web-server
      dockerfile: Dockerfile
    container_name: video-streaming-webserver
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: "no"